### ISSUE TITLE
Support of Parquet

### ISSUE THREAD

**Issue by erubichi-quotient** [pipecraft/pipes#2]
Hi :)
Is there a plan anytime soon to support Parquet files as input?

**Comment by eyalschneider** [comment]
Yes, in the next version (0.92) I intend to introduce two new encoders/decoders: protobuf and Parquet.

**Comment by eyalschneider** [comment]
@erubichi-quotient : I've been reading about it and experimenting a little. Unfortunately, documentation (in code and outside) is very poor, many examples from blog posts are outdated, and it seems like it's not possible to avoid Hadoop dependencies (additional jars and even environment settings) at the moment. See also [this old open issue](https://issues.apache.org/jira/browse/PARQUET-1126).
I don't think I will include it in the next Pipes version. If you find a working stand-alone read/write example, please let me know.

**Comment by erubichi-quotient** [comment]
Thanks!
